changelog:
  categories:
    - title: Features
      labels:
        - enhancement
        - feature
    - title: Fixes
      labels:
        - bug
        - fix
    - title: Documentation
      labels:
        - documentation
        - docs
    - title: CI / Build
      labels:
        - ci
        - build
    - title: Other changes
      labels:
        - "*"
  exclude:
    labels:
      - skip-changelog
